/**
 * BE engine (Phase A computational core) — public surface.
 *
 * Wiring contract (the follow-up session): the ONLY production writer is
 * StoryStore.applyClassificationResult() calling reduceCharacterBody(); templates,
 * image prompts, and UI read via the derivations. See ambrosia-st research/31 §2.
 */

export * from './types'
export {
  ANTICIPATION_THRESHOLD,
  APPARENT_TIER_ENGORGED,
  APPARENT_TIER_PRESSURE_PRONE,
  CHECK_DEBUFF_CONDITION_PREFIX,
  CHECK_DEBUFF_DC_PENALTY,
  CHRONIC_SUPPLY_BEATS,
  CHRONIC_SUPPLY_TIER,
  DEFAULT_BE_STORY_CONFIG,
  DEFAULT_FLUID_PROFILE,
  DEFAULT_GROWTH_COOLDOWN_BEATS,
  EARLY_BLOOMER_INDUCTION_BONUS,
  ENGORGED_FILL_THRESHOLD,
  ENGORGED_FILL_THRESHOLD_PRESSURE_PRONE,
  ENGORGED_TTL,
  FLUID_REGISTRY,
  GROWTH_DELTA_BY_OUTCOME,
  GROWTH_EVENT_KINDS,
  GROWTH_INTENT_BASE_INTENSITY,
  GRUDGE_STALL_THRESHOLD,
  GUARANTEED_GROWTH_ROLL,
  MAX_BE_CONDITIONS,
  MAX_BE_EVENTS_PER_TURN,
  MILK_UNIT_ML,
  OVERFILL_ADD_BASE,
  OVERFILL_FILL_THRESHOLD,
  PRESSURE_ACCRUAL,
  PRESSURE_FIRE,
  PRESSURE_RELEASE,
  SPELL_BAND_INTENSITY_DELTA,
  SUPPLY_ADAPT_UP_BEATS,
  SUPPLY_EASE_IDLE_BEATS,
  SUPPLY_FILL_RATE_BONUS,
  SUPPLY_LABELS,
  SUPPLY_SURGE_MAX_DELTA,
  SUPPLY_TIER_MAX,
  fluidProfile,
  parseGrowthEligibleKinds,
  type FluidProfile,
  GROWTH_BONUS_NOTE,
  DEFAULT_GROWTH_BASELINE_CM,
  GROWTH_BASELINE_CM_MAX,
  GROWTH_BASELINE_CM_MIN,
  MAX_GROWTH_BONUS_CM,
  SPELL_GROWTH_CM_PER_INTENSITY,
  beStoryConfigFromSettings,
  clampGrowthBaselineCm,
  GROWTH_TRIGGER_BLOCK_NOTE,
} from './constants'
export { buildBeGenreRules, type BeGenreRuleOptions } from './genre-rules'
export {
  IMAGE_SIZE_ANCHOR_PHRASES,
  bandIndex,
  bandPosition,
  bandWord,
  comparative,
  cupLetter,
  groundImagePromptSize,
  imageSizeAnchor,
  imageSizeAnchorRung,
  imageSizePhrase,
  sniffTierFromText,
  tierForCupLetter,
} from './ladder'
export { parseBuildLabel, parseHeightCm, seedBaselineFromText } from './baseline'
export { BAND_WORD_THRESHOLDS } from './ladder-data'
export { groundingFacts } from './derive'
export {
  BAND_SPRITE_TIER,
  SPRITE_AROUSAL_FLUSH_THRESHOLD,
  bandRepresentativeTier,
  selectSprite,
  spriteAppearanceHash,
  spriteSeed,
  type SpriteAppearanceInput,
  type SpriteExpression,
  type SpriteSelection,
} from './sprite'
export {
  bandCm,
  bodyRow,
  bustCm,
  bustDiffCm,
  bwhCmString,
  capacityMlPerSide,
  droopCm,
  dryBustCm,
  dryBustNote,
  dryKgPerSide,
  effectiveSupport,
  fluidPressureLabel,
  imageStateCues,
  measurements,
  nowKgPerSide,
  proportionNote,
  resolveBuild,
  sizingString,
  weightFeel,
} from './measurements'
export { reduceCharacterBody } from './reducer'
export { previewGuaranteedGrowth, type GuaranteedGrowthPreviewInput } from './preview'
export {
  CRIT_MARGIN,
  CRIT_NAT,
  PARTIAL_MISS_WINDOW,
  resolveCheckBand,
  resolveGrowthOutcome,
  seededRoll,
  type CheckBand,
} from './roll'
export {
  beConditionSchema,
  beConditionsFromResult,
  beEventSchema,
  beEventsFromResult,
  beSoftStateSchema,
  beSoftStatesFromResult,
  bondEventSchema,
  bondEventsFromResult,
  buildBeEventInstructions,
  exposureEventSchema,
  exposureEventsFromResult,
  extendClassificationSchemaWithBeEvents,
  growthTriggerSchema,
  growthTriggersFromResult,
  type BeCharacterCondition,
} from './schema'
export {
  actGrowthCm,
  bankBonusCm,
  bonusCmForIntensity,
  cmPerTierAt,
  fmtCm,
  previewActGrowth,
  safeBonusCm,
  safeCarryCm,
  tiersForCm,
} from './magnitude'
export {
  GROWTH_TRIGGER_MIN_EVIDENCE_CHARS,
  GROWTH_TRIGGER_MIN_EVIDENCE_WORDS,
  growthGateRequired,
  normalizeEvidenceText,
  nameTokensOf,
  normalizeTriggerName,
  projectForMatch,
  verifyGrowthTriggers,
  type GrowthTriggerRejection,
  type GrowthTriggerVerification,
  type VerifyGrowthTriggersOptions,
} from './trigger'
export {
  buildBeStateBlock,
  buildHaremStateBlock,
  HAREM_STATE_HEADER,
  type BeStateEntry,
} from './context'
export {
  PRESENCE_LOOKBACK,
  effectivePresence,
  normalizePresenceName,
  readScenePresence,
  recentPresenceUnion,
  referencedCharacterNames,
  selectScenePresent,
  type EffectivePresenceInput,
  type PresenceEntrySource,
} from './presence'
export {
  applyRelationshipTurn,
  applyExposure,
  bondCheckModifier,
  bondOf,
  bondStance,
  clampBond,
  clampTrack,
  decayDependence,
  dependenceOf,
  dependenceStage,
  relOf,
  stanceBlurb,
  withdrawalCondition,
  type BondStance,
  type DependenceStage,
  type RelationshipTurnResult,
  type TrackDelta,
} from './tracks'
export {
  assignQuirks,
  hasQuirk,
  QUIRK_BY_ID,
  QUIRK_IDS,
  QUIRKS,
  readQuirks,
  type QuirkDef,
  type QuirkId,
} from './quirks'
export {
  adaptSupply,
  apparentTier,
  apparentTierBonus,
  engorgeThreshold,
  findMilkItem,
  isEngorged,
  lactationOf,
  milkItemMetadata,
  milkItemName,
  milkYieldUnits,
  qualityFromBand,
  supplyFillMultiplier,
  supplyLabel,
  supplyMeter,
  tickChronic,
  type ChronicTick,
  type MilkItemLike,
  type MilkQuality,
  type SupplyAdapt,
  type SupplyMeterView,
} from './lactation'
export {
  EFFECT_KINDS,
  coerceEffectTags,
  dedupeForCast,
  effectTagSchema,
  promoteGrowthIntent,
  translateSpellEffects,
  type EffectKind,
  type EffectTag,
  type SpellTranslation,
} from './effects'
export { detectDrift } from './drift'
export { INTERACTION_MILESTONES, nextMilestone, type InteractionMilestone } from './milestones'
export {
  BODY_STATE_KEY,
  DEFAULT_FLUID_TYPE,
  bodyStateSchema,
  defaultBodyState,
  maxBodyStateTier,
  readBodyState,
  seedBodyStateFromCup,
  soloBodyState,
  uniformBodyStateTier,
  writeBodyState,
} from './metadata'
